import {
    faTimes,
    faImage,
    faCheck,
    faPlus,
    faTrash,
    faSave,
    faEdit,
    faFilter,
    faEye,
    faWallet,
    faUsers,
    faUser,
    faComment,
    faPaperclip,
    faPaperPlane,
    faBars,
    faCompass, 
    faTrophy,
    faCog,
    faFire,
    faDove,
    faSun,
    faBell,
    faUndoAlt
} from '@fortawesome/free-solid-svg-icons'

export default [
    { icon: faTimes, code: 'faTimes' },
    { icon: faImage, code: 'faImage' },
    { icon: faCheck, code: 'faCheck' },
    { icon: faPlus, code: 'faPlus' },
    { icon: faTrash, code: 'faTrash' },
    { icon: faSave, code: 'faSave' },
    { icon: faEdit, code: 'faEdit' },
    { icon: faFilter, code: 'faFilter' },
    { icon: faEye, code: 'faEye' },
    { icon: faWallet, code: 'faWallet' },
    { icon: faUsers, code: 'faUsers' },
    { icon: faUser, code: 'faUser' },
    { icon: faComment, code: 'faComment' },
    { icon: faPaperclip, code: 'faPaperclip' },
    { icon: faPaperPlane, code: 'faPaperPlane' },
    { icon: faBars, code: 'faBars' },
    { icon: faCompass, code: 'faCompass' },
    { icon: faTrophy, code: 'faTrophy' },
    { icon: faCog, code: 'faCog' },
    { icon: faFire, code: 'faFire' },
    { icon: faDove, code: 'faDove' },
    { icon: faSun, code: 'faSun' },
    { icon: faBell, code: 'faBell' },
    { icon: faUndoAlt, code: 'faUndoAlt' }
]