export default {
    SET_USER: 'SET_USER',
    SET_FORM: 'SET_FORM',
    SET_DATA_TABLE: 'SET_DATA_TABLE',
    SET_DOCUMENT: 'SET_DOCUMENT',
    SET_DOCUMENTS: 'SET_DOCUMENTS',

    ADD_OFFER: 'ADD_OFFER',

    SET_CHAT: 'SET_CHAT',
    CLOSE_CHAT: 'CLOSE_CHAT'
}